x-common-environment: &common-env
  NATS_URL: nats://nats:4222
  SENSORKIT_DEBUG: 1
  SENSORKIT_IMPORTS: >-
    sensorkit.alpaca.service,
    sensorkit.pwi4.service,
    sensorkit.otto.models,
    sensorkit.node_platform.service,
    sensorkit.slack.models

services:
  nats:
    image: nats:2.12-alpine
    ports:
      - "4222:4222"
    command: "-js -m 8222"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8222/varz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  planewave-sim:
    build: pwi4
    image: pwi4-sim
    pull_policy: never
    ports:
      - "8220:8220"
      - "6080:6080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8220"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  ascom-sim:
    build: ascom
    image: ascom-sim
    pull_policy: never
    ports:
      - "30000:32323"
    command: "dotnet ascom.alpaca.simulators.dll"
    restart: unless-stopped

  ascom-sim2:
    build: ascom
    image: ascom-sim
    pull_policy: never
    ports:
      - "30001:32323"
    command: "dotnet ascom.alpaca.simulators.dll"
    restart: unless-stopped

  reload-config:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    image: sensorkit
    pull_policy: never
    depends_on:
      nats:
        condition: service_healthy
      planewave-sim:
        condition: service_healthy
      ascom-sim:
        condition: service_started
    command: config load -v /opt/sensorkit.yaml
    environment:
      <<: *common-env
    volumes:
      - ./sensorkit.yaml:/opt/sensorkit.yaml:ro

  agent:
    image: sensorkit
    pull_policy: never
    command: service run agent sensorkit.auto.agent
    environment:
      <<: *common-env
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully
      sensor:
        condition: service_started
      planewave:
        condition: service_started
      alpaca:
        condition: service_started

  webapi:
    image: sensorkit
    pull_policy: never
    ports:
      - "8000:8000"
    command: service run WebAPI sensorkit.webapi
    environment:
      <<: *common-env
    volumes:
      - ./tmp:/opt/data
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully

  sensor:
    image: sensorkit
    pull_policy: never
    command: service run SimulatedSensor sensorkit.sensor
    environment:
      <<: *common-env
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully

  alpaca:
    image: sensorkit
    pull_policy: never
    command: service run Alpaca sensorkit.alpaca.service
    environment:
      <<: *common-env
      NATS_URL: nats://localhost:4222
    network_mode: "host"  # So that "localhost" config also works for baremetal
    volumes:
      - ./tmp:/opt/data
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully

  planewave:
    image: sensorkit
    pull_policy: never
    command: service run PlaneWave sensorkit.pwi4.service
    environment:
      <<: *common-env
      NATS_URL: nats://localhost:4222
    network_mode: "host"  # So that "localhost" config also works for baremetal
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully

  program:
    image: sensorkit
    pull_policy: never
    command: service run SimulatedProgram /app/program.py
    environment:
      <<: *common-env
    volumes:
      - ./program.py:/app/program.py
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully

  otto:
    image: sensorkit
    pull_policy: never
    command: service run Otto sensorkit.otto.program
    environment:
      <<: *common-env
    restart: unless-stopped
    depends_on:
      reload-config:
        condition: service_completed_successfully
