version: 1

automation:
  first_run:
    operate_all: true
    enable_scheduling: true

  controllers:
    SimulatedSensor:
      estimated_startup_time: 60

      modes:
        - name: default
          description: Operational mode
          state: operate
          criteria:
            - when: tasking_available

        - name: keepalive
          description: Standby mode
          state: operate
          criteria:
            - when: after_activity
              duration: 1m

      constraints:
        - kind: weather
          hold: 5.0
          provider: SimulatedWeather
          humidity_max: 75.0
          humidity_deadband: 1.0
          wind_max: 12.0
          wind_deadband: 1.0
        - kind: conditional
          hold: 10.0
          optional: true
          entity: SimulatedWeather
          keyword: BasicWeather
          field: humidity
          condition:
            kind: above
            threshold: 75.0
            deadband: 2.0

      tasking:
        - program: SimulatedProgram
          priority: 1
        - program: Burr
          priority: 2

  contexts:
    standard_collect:
      file_name: f"{datetime.now(UTC):%Y%m%dT%H%M%S}-f{frame_num}.fits"
    
data_flow:
  - entity: SimulatedCamera
    producer:
      simple:
        - op: app_source
        - op: array_to_fits
          header:
            BSCALE: "1"
            BITPIX: bitpix
            BZERO: bzero
            TASKID: task_id
            FRAMENUM: frame_num
            CENTAZ: az
            CENTALT: alt
            RADEG: ra
            DECDEG: dec
        - op: write_file
          directory: f"C:\\Temp\\SimulatedCamera"

sensors:
  - id: SimulatedSensor

    devices:
      mount: SimulatedMount
      camera: SimulatedCamera
      dome: SimulatedDome
      filter_wheel: SimulatedFilterWheel
      rotator: SimulatedRotator
      focuser: SimulatedFocuser

    site_position:
      latitude_degrees: 36.063067
      longitude_degrees: -115.144828
      altitude_km: .05

    policies:
      concurrent_dome_and_mount_init: false
      concurrent_dome_and_mount_deinit: false
      dome_open_close_timeout: 120.0
      concurrent_mount_and_mirror_cover_init: false
      mirror_cover_open_close_timeout: 60.0
      mount_init_timeout: 30.0
      mount_home_timeout: 300.0

    controller_name: ""

otto:
  - id: Otto
    entity: Otto
    controller: SimulatedSensor
    task:
      objects: [ "21639" ]
      tle_update_interval_hours: 4
      graylist_interval_minutes: 15
      end_time_deadband_seconds: 300
    collect:
      altitude_min: 20
      track_mode: rate_sidereal
      dither: false
      dither_amount_arcsec: 500
      filters: [ ]
      exposure_min: 4
      exposure_max: 5
      exposure_delta: 1
      binning: [ 2 ]
      num_frames: 3
    publish:
      upload: true
      sensor_name: "SK-TEST"
    server:
      host: "localhost"
      port: 8070

alpaca:
  - id: Alpaca
    endpoints:
      - host: localhost
        port: 30000
        protocol: http
        devices:
          SimulatedCamera:
            device_type: camera
            device_number: 0
            status_frequency: 1.0
          SimulatedDome:
            device_type: dome
            device_number: 0
            status_frequency: 1.0
          SimulatedFilterWheel:
            device_type: filter_wheel
            device_number: 0
            status_frequency: 1.0
          SimulatedRotator:
            device_type: rotator
            device_number: 0
            status_frequency: 1.0
          SimulatedFocuser:
            device_type: focuser
            device_number: 0
            status_frequency: 1.0
          SimulatedWeather:
            device_type: observing_conditions
            device_number: 0
            status_frequency: 1.0

pwi4:
  - id: PlaneWave
    endpoints:
    - host: localhost
      port: 8220
      devices:
        SimulatedMount:
          device_type: mount
          status_frequency: 1.0
          park_absolute: true
          park_axis0_degrees: 30
          park_axis1_degrees: 0

burr:
  - id: Burr
    controller: SimulatedSensor
    schedule:
      twilight_flats:
        windows:
          - nautical_twilight
        collect: true
      calsats:
        windows:
          - night
          - astronomical_twilight
        collect: true
        tle_provider: spacebook
      photometric_standards:
        windows:
          - day
          - night
        minimum_exposure_seconds: 1
        maximum_exposure_seconds: 10
        n_exposures: 10
        minimum_altitude_degrees: 30
        collect: true
      streaks:
        collect: true
        minimum_length_pixel: 5
        maximum_length_pixel: 100
    plotting:
      debug: true
      review: true
    runtime:
      output_dir: "/temp/burr/"

config:
  SimulatedSensor:
    SitePosition:
      latitude_degrees: 36.063067
      longitude_degrees: -115.144828
      altitude_km: .05

services:
  - id: WebAPI
    python_module: sensorkit.webapi
  - id: SimulatedProgram
    python_module: deploy/simulated/program.py
