entity: agent
key: AgentConfig
value:
  first_run:
    operate_all: false
    enable_scheduling: true
  controllers:
    sim_sensor:
      estimated_startup_time: 60

      modes:
        - name: default
          description: Operational mode
          state: operate
          criteria:
            - kind: tasking_available

        - name: keepalive 
          description: Standby mode
          state: operate
          criteria:
            - kind: after_activity
              duration: 1m

      constraints:
        - kind: weather
          provider: sim_weather
          humidity_max: 75.0
          humidity_deadband: 1.0
          wind_max: 12.0
          wind_deadband: 1.0

      tasking:
        - program: sim_program
          priority: 10

  contexts:
    standard_collect:
      file_name: f"{datetime.now(UTC):%Y%m%dT%H%M%S}-f{frame_num}.fits"
