entity: ascom_service
key: AscomConfig
value:
  endpoints:
    - host: alpaca-sim
      port: 32323
      protocol: http
      devices:
        - entity: sim_camera
          device_type: camera
          device_number: 0
          status_frequency: 1.0
        - entity: sim_dome
          device_type: dome
          device_number: 0
          status_frequency: 1.0
        - entity: sim_fw
          device_type: filterwheel 
          device_number: 0
          status_frequency: 1.0
        - entity: sim_rotator
          device_type: rotator
          device_number: 0
          status_frequency: 1.0
        - entity: sim_focuser
          device_type: focuser
          device_number: 0
          status_frequency: 1.0
        - entity: sim_weather
          device_type: observingconditions
          device_number: 0
          status_frequency: 1.0