entity: sim_camera
key: DataGraph
value:
  simple:
    - op: app_source
    - op: array_to_fits
      header:
        BSCALE: "1"
        BITPIX: bits_per_pixel
        BZERO: zero_value
        TASKID: task_id
        FRAMENUM: frame_num
        CENTAZ: az
        CENTALT: alt
        RADEG: ra
        DECDEG: dec
    - op: write_file
      directory: f"/tmp"
